version: "3.8"
services:
  db:
    container_name: travel_db
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=travel
      - MYSQL_USER=travel
      - MYSQL_PASSWORD=travel
      - MYSQL_ROOT_PASSWORD=travel
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
