"""Add attrib location to Monument

Revision ID: 2c078de48c6c
Revises: 4272bd73dd11
Create Date: 2025-03-04 16:14:52.849644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c078de48c6c'
down_revision: Union[str, None] = '4272bd73dd11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monument', sa.Column('location', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('monument', 'location')
    # ### end Alembic commands ###
