"""Make tag_id primary key in UserPreference

Revision ID: 4272bd73dd11
Revises: ededcd19caec
Create Date: 2025-03-04 15:32:48.775798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4272bd73dd11'
down_revision: Union[str, None] = 'ededcd19caec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
