"""Added Monument type, image, desc

Revision ID: 8c6a5a69cabb
Revises: 758ecf9cbcdf
Create Date: 2025-03-03 21:36:53.104190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8c6a5a69cabb'
down_revision: Union[str, None] = '758ecf9cbcdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monument', sa.Column('type', sa.String(length=255), nullable=True))
    op.add_column('monument', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('monument', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_column('monument', 'events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('monument', sa.Column('events', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('monument', 'image_url')
    op.drop_column('monument', 'description')
    op.drop_column('monument', 'type')
    # ### end Alembic commands ###
