"""Made tag_id and user_id composite key

Revision ID: ededcd19caec
Revises: 8c6a5a69cabb
Create Date: 2025-03-04 15:28:27.249772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ededcd19caec'
down_revision: Union[str, None] = '8c6a5a69cabb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_preference', 'tag_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_preference', 'tag_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
